<?php

function greetings_menu() {
    $different_variable = [];
    $different_variable['hello_friend'] = [
        'title' => 'Hello Friend!',
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    ];
    $different_variable['goodbye_friend'] = [
        'title' => 'Goodbye Friend!',
        'page callback' => 'say_goobye',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    ];
    return $different_variable;

}

function say_hello () {
    return '<p>Hello my dear friend!</p>';
}

function say_goobye() {
    return '<p>Goodbye my dear friend!</p>';
}

function greetings_user_login() {
    $_GET['destination'] = 'hello_friend';
}

function greetings_user_logout() {
    $_GET['destination'] = 'goodbye_friend';
}
